# Generated by Django 4.1.5 on 2023-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cheeseoption_sauceoption_remove_pizzasize_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
