# Generated by Django 4.1.5 on 2023-02-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cheese_crust_sauce_size_topping_alter_pizza_id_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
