# Generated by Django 4.1.5 on 2023-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_customerinfo_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
