# Generated by Django 4.1.5 on 2023-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_customerinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('ham', 'Ham')], default='Tomato', max_length=20),
        ),
    ]
