# Generated by Django 4.1.5 on 2023-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_sauce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(default='Tomato', max_length=20),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('ham', 'Ham')], max_length=20),
        ),
    ]
