# Generated by Django 4.1.5 on 2023-02-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_sauce_name_alter_topping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(default='Ham', max_length=20),
        ),
    ]
