# Generated by Django 4.1.5 on 2023-02-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_topping_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='name',
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
