# Generated by Django 4.1.5 on 2023-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_topping_name_alter_topping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(default='Ham', max_length=20),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
