# Generated by Django 4.1.5 on 2023-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_topping_name_alter_topping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('chicken', 'Chicken'), ('ham', 'Ham'), ('pineapple', 'Pineapple'), ('peppers', 'Peppers'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions')], default='pepperoni', max_length=20),
        ),
    ]
