# Generated by Django 4.1.5 on 2023-02-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_topping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(default='Ham', max_length=20),
        ),
    ]
