# Generated by Django 4.1.5 on 2023-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_topping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Pineapple', 'Pineapple'), ('Peppers', 'Peppers'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions')], default='Pepperoni', max_length=20),
        ),
    ]
